Add required 'labels' property to FakeProvider
Without this, following `CONTRIBUTING.md` for setup
without a kubernetes cluster fails with the following
error message:

```
  File "/Users/yuvipanda/code/binderhub/binderhub/templates/index.html", line 42, in block 'form'
    <label for="repository">{{(repo_providers.values() | list | first).labels.text}}</label>
  File "/Users/yuvipanda/.local/share/virtualenvs/binderhub/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'traitlets.traitlets.MetaHasTraits object' has no attribute 'labels'
```